----@ "C:\Users\HERO-INFO\Desktop\M1-sii\s2\bdd\projet bdd 2024-2025\bda-project\bdd-project\Script-Ligne.sql"
INSERT INTO Ligne VALUES ('B001', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S001'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S004'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'BUS'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('M001', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S001'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S004'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'MET'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('TM001', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S003'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S006'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRM'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('TN001', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S005'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S009'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRN'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('B002', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S007'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S010'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'BUS'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('M002', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S007'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S010'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'MET'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('TM002', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S007'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S010'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRM'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('TN002', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S005'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S010'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRN'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('B003', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S013'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S016'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'BUS'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('M003', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S013'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S016'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'MET'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('TM003', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S013'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S016'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRM'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('TN003', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S013'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S016'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRN'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('B004', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S018'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S004'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'BUS'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('M004', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S018'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S004'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'MET'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('TM004', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S018'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S004'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRM'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('TN004', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S018'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S004'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRN'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('B005', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S007'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S008'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'BUS'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('TN005', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S019'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S015'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRN'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('B006', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S019'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S014'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'BUS'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('TM005', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S020'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S021'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRM'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('M005', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S021'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S023'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'MET'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('TM006', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S022'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S023'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRM'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('TN006', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S022'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S019'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRN'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
INSERT INTO Ligne VALUES ('M006', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S023'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S016'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'MET'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());


-- This line is intentionally incorrect to trigger the verification constraint
-- la station  d'arrivee dessert le moyen de transport choisi
INSERT INTO Ligne VALUES ('TN002', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S007'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S008'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRN'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
 --la station DE depart ne dessert pas ce moyen de transport choisi
INSERT INTO Ligne VALUES ('TN002', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S008'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S007'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRN'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());
-- la station de depart et d'arrivee sont les memes
INSERT INTO Ligne VALUES ('TN002', (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S007'), (SELECT REF(s) FROM Station s WHERE s.CodeStation = 'S007'), (SELECT REF(m) FROM Moytransport m WHERE m.Abreviation = 'TRN'), T_Set_Ref_Troncon(), T_Set_Ref_Navette());