--@ "C:\Users\HERO-INFO\Desktop\M1-sii\s2\bdd\projet bdd 2024-2025\bda-project\bdd-project\Script-Station.sql"
-- --------------------------------------------------Insertion dans la table station:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO Station VALUES ('S001', 'Station A',TCoordonnees(38.8566, 2.3522), 1,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='BUS'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='MET'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRM'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN'))) ;
INSERT INTO Station VALUES ('S002', 'Station B',TCoordonnees(58.8570, 2.3530), 0,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='MET')));
INSERT INTO Station VALUES ('S003', 'Station C',TCoordonnees(48.8575, 7.3540), 0, T_Set_Ref_Ligne(), T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRM')));
INSERT INTO Station VALUES ('S004', 'Station D',TCoordonnees(78.8580, 2.3550), 1, T_Set_Ref_Ligne(), T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='BUS'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='MET'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRM'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN')));
INSERT INTO Station VALUES ('S005', 'Station E',TCoordonnees(88.8590, 2.3560), 0,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN')));
INSERT INTO Station VALUES ('S006', 'Station F',TCoordonnees(48.8600, 3.3570), 0,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRM')));
INSERT INTO Station VALUES ('S007', 'Station G',TCoordonnees(48.8610, 2.3580), 1,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='BUS'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='MET'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRM'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN')));
INSERT INTO Station VALUES ('S008', 'Station H',TCoordonnees(38.8620, 2.3590), 0,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='BUS')));
INSERT INTO Station VALUES ('S009', 'Station I',TCoordonnees(48.8630, 2.3600), 0,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN')));
INSERT INTO Station VALUES ('S010', 'Station J',TCoordonnees(48.8640, 5.3610), 1,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='BUS'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='MET'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRM'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN')));
INSERT INTO Station VALUES ('S011', 'Station K',TCoordonnees(58.8650, 2.3620), 0,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='MET')));
INSERT INTO Station VALUES ('S012', 'Station L',TCoordonnees(48.8660, 2.3630), 0,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN')));
INSERT INTO Station VALUES ('S013', 'Station M',TCoordonnees(48.8670, 2.3640), 1,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='BUS'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='MET'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRM'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN')));
INSERT INTO Station VALUES ('S014', 'Station N',TCoordonnees(48.8680, 8.3650), 0,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='BUS')));
INSERT INTO Station VALUES ('S015', 'Station O',TCoordonnees(48.8690, 2.3660), 0,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN')));
INSERT INTO Station VALUES ('S016', 'Station P',TCoordonnees(48.8700, 9.3670), 1,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='BUS'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='MET'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRM'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN')));
INSERT INTO Station VALUES ('S017', 'Station Q',TCoordonnees(48.8710, 2.3680), 0,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='MET')));
INSERT INTO Station VALUES ('S018', 'BEZ',TCoordonnees(42.2557, 3.3550), 1,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='BUS'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='MET'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRM'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN')));
INSERT INTO Station VALUES ('S019', 'Station R',TCoordonnees(78.8720, 2.3690), 1,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='BUS')));
INSERT INTO Station VALUES ('S020', 'Station S',TCoordonnees(48.8730, 3.3700), 1,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRM'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN')));
INSERT INTO Station VALUES ('S021', 'Station T',TCoordonnees(48.8740, 4.3710), 1,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='MET'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRM')));
INSERT INTO Station VALUES ('S022', 'Station U',TCoordonnees(48.8750, 5.3720), 1,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='BUS'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRM')));
INSERT INTO Station VALUES ('S023', 'Station V',TCoordonnees(48.8760, 6.3730), 1,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRM'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='MET')));
--si principle =1 alors il faut au moins 2 moyens de transport
--Verification de la contrainte d'integrite de la table station si EstPrincipale=1 Au moins 2 moyens de transport
INSERT INTO Station VALUES ('S000', 'Station X',TCoordonnees(58.8566, 3.3522), 1,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen()) ;
--si EstPrincipale=1 alors il faut au moins 2 moyens de transport
INSERT INTO Station VALUES ('S000', 'Station X',TCoordonnees(58.8566, 3.3522), 1,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='BUS'))) ;
--VERIFICATION DE LA CONTRAINTE D'INTEGRITE DE LA TABLE STATION SI ESTPRINCIPALE=0 AU moins 1 MOYEN DE TRANSPORT
INSERT INTO Station VALUES ('S000', 'Station Y',TCoordonnees(58.8566, 3.3522), 0,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen()) ;
--si EstPrincipale=0 alors il faut au plus 1 moyen de transport
INSERT INTO Station VALUES ('S024', 'Station Z',TCoordonnees(38.8566, 2.3522), 0,T_Set_Ref_Ligne(),T_Set_Ref_Troncon(),T_Set_Ref_Moyen((SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='BUS'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='MET'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRM'),(SELECT REF(m) FROM Moytransport m WHERE m.Abreviation='TRN'))) ;
